import React, { useState } from 'react';

export default function ResumeAnalyzer() {
  const [file, setFile] = useState(null);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [error, setError] = useState(null);
  const [analysis, setAnalysis] = useState(null);

  const handleFileChange = (e) => {
    const selectedFile = e.target.files[0];
    if (selectedFile && selectedFile.type === 'application/pdf') {
      setFile(selectedFile);
      setError(null);
    } else {
      setError('Please select a valid PDF file.');
      setFile(null);
    }
  };

  const getBase64 = (file) => {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.readAsDataURL(file);
      reader.onload = () => resolve(reader.result.split(',')[1]);
      reader.onerror = (error) => reject(error);
    });
  };

  const handleUpload = async () => {
    if (!file) return;

    setIsAnalyzing(true);
    setError(null);
    setAnalysis(null);

    try {
      const base64Data = await getBase64(file);

      const response = await fetch('http://localhost:5000/api/ai/analyze-resume', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({ pdfBase64: base64Data })
      });

      const result = await response.json();

      if (!response.ok) {
        throw new Error(result.message || 'Failed to analyze resume.');
      }

      setAnalysis(result.data);
    } catch (err) {
      console.error(err);
      setError(err.message || 'An error occurred during resume analysis. Please verify your backend server and Gemini API keys.');
    } finally {
      setIsAnalyzing(false);
    }
  };

  const downloadReport = () => {
    if (!analysis) return;

    const reportText = `
DEVMENTOR AI - RESUME ANALYSIS REPORT
=====================================
ATS Score: ${analysis.atsScore}/100
Evaluation Summary:
${analysis.summary}

Missing Skills Suggested:
${analysis.missingSkills.map(skill => `- ${skill}`).join('\n')}

Actionable Recommendations / Improvements:
${analysis.improvements.map(imp => `- ${imp}`).join('\n')}

Generated by DevMentor AI.
    `.trim();

    const blob = new Blob([reportText], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${file.name.replace('.pdf', '')}_ats_report.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-8 animate-fade-in pb-12">
      {/* Page Header */}
      <div className="border-b border-slate-800/60 pb-6">
        <h1 className="text-3xl font-extrabold text-white tracking-tight">AI Resume Analyzer</h1>
        <p className="text-slate-400 mt-2">Evaluate your CV against technical recruitment standards and discover missing skills.</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        
        {/* Upload Zone */}
        <div className="lg:col-span-1 space-y-6">
          <div className="bg-slate-900/50 border border-slate-800 rounded-3xl p-6 shadow-xl relative overflow-hidden">
            <div className="absolute top-0 right-0 w-32 h-32 bg-indigo-500/5 rounded-full blur-3xl pointer-events-none"></div>
            
            <div className="space-y-4">
              <h3 className="text-lg font-bold text-white">Upload Resume</h3>
              
              <label className="flex flex-col items-center justify-center border-2 border-dashed border-slate-700 hover:border-indigo-500/50 rounded-2xl p-6 cursor-pointer hover:bg-slate-800/20 transition-all duration-300 group">
                <svg className="w-10 h-10 text-slate-500 group-hover:text-indigo-400 transition-colors mb-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12" />
                </svg>
                <span className="text-sm font-semibold text-slate-300">Select PDF File</span>
                <span className="text-xs text-slate-500 mt-1">Only PDF formats supported</span>
                <input 
                  type="file" 
                  accept=".pdf" 
                  onChange={handleFileChange} 
                  className="hidden" 
                />
              </label>

              {file && (
                <div className="bg-slate-950 border border-slate-800 rounded-xl p-3 flex items-center justify-between">
                  <div className="flex items-center gap-3 min-w-0">
                    <svg className="w-5 h-5 text-indigo-400 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                    </svg>
                    <span className="text-xs text-slate-300 truncate font-mono">{file.name}</span>
                  </div>
                  <span className="text-[10px] text-slate-500 font-medium">{(file.size / (1024 * 1024)).toFixed(2)} MB</span>
                </div>
              )}

              {error && (
                <div className="bg-red-500/10 border border-red-500/20 text-red-400 text-xs px-4 py-3 rounded-xl flex items-start gap-2">
                  <svg className="w-4 h-4 shrink-0 mt-0.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                  </svg>
                  <span>{error}</span>
                </div>
              )}

              <button
                onClick={handleUpload}
                disabled={!file || isAnalyzing}
                className="w-full bg-indigo-600 hover:bg-indigo-500 disabled:opacity-50 text-white font-bold py-3 rounded-xl shadow-lg shadow-indigo-600/20 transition-all flex items-center justify-center gap-2 cursor-pointer"
              >
                {isAnalyzing ? (
                  <>
                    <svg className="w-5 h-5 animate-spin" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
                    </svg>
                    Analyzing CV...
                  </>
                ) : (
                  'Analyze Resume'
                )}
              </button>
            </div>
          </div>
        </div>

        {/* Results Area */}
        <div className="lg:col-span-2 space-y-6">
          {analysis ? (
            <div className="space-y-8 animate-fade-in">
              
              {/* Top Row: Score & Summary */}
              <div className="grid grid-cols-1 md:grid-cols-3 gap-6 items-stretch">
                {/* Score Dial Card */}
                <div className="bg-slate-900/50 border border-slate-800 rounded-3xl p-6 flex flex-col items-center justify-center text-center shadow-xl">
                  <span className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-4">ATS Fit Score</span>
                  <div className="relative w-36 h-36 flex items-center justify-center">
                    {/* Ring Path background */}
                    <div className="absolute inset-0 rounded-full border-8 border-slate-800"></div>
                    {/* Glowing Accent Border representing score */}
                    <div className="absolute inset-0 rounded-full border-8 border-indigo-500/80 animate-pulse shadow-[0_0_15px_rgba(99,102,241,0.3)]"></div>
                    
                    <span className="text-4xl font-extrabold text-white tracking-tight">{analysis.atsScore}%</span>
                  </div>
                  <span className="text-xs text-indigo-400 font-semibold mt-4">Optimized Rating</span>
                </div>

                {/* Evaluation Overview */}
                <div className="md:col-span-2 bg-slate-900/50 border border-slate-800 rounded-3xl p-6 flex flex-col justify-between shadow-xl">
                  <div>
                    <span className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-2 block">Evaluation Summary</span>
                    <p className="text-slate-300 leading-relaxed">{analysis.summary}</p>
                  </div>
                  <button 
                    onClick={downloadReport}
                    className="w-max mt-4 text-xs font-bold text-indigo-400 hover:text-indigo-300 flex items-center gap-1.5 transition-colors border border-indigo-500/20 bg-indigo-500/5 hover:bg-indigo-500/10 px-3.5 py-2 rounded-xl"
                  >
                    <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                    </svg>
                    Download Analysis Report
                  </button>
                </div>
              </div>

              {/* Skills & Improvements Lists */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                
                {/* Missing Skills */}
                <div className="bg-slate-900/50 border border-slate-800 rounded-3xl p-6 shadow-xl space-y-4">
                  <h3 className="text-lg font-bold text-white flex items-center gap-2">
                    <span className="w-2.5 h-2.5 rounded-full bg-amber-500"></span>
                    Missing Tech Skills
                  </h3>
                  <div className="flex flex-wrap gap-2">
                    {analysis.missingSkills.map((skill, idx) => (
                      <span 
                        key={idx}
                        className="px-3 py-1.5 rounded-xl bg-slate-950 border border-slate-800 text-xs font-medium text-amber-400"
                      >
                        {skill}
                      </span>
                    ))}
                  </div>
                </div>

                {/* Suggested Improvements */}
                <div className="bg-slate-900/50 border border-slate-800 rounded-3xl p-6 shadow-xl space-y-4">
                  <h3 className="text-lg font-bold text-white flex items-center gap-2">
                    <span className="w-2.5 h-2.5 rounded-full bg-indigo-500"></span>
                    Key Recommendations
                  </h3>
                  <ul className="space-y-3">
                    {analysis.improvements.map((imp, idx) => (
                      <li key={idx} className="text-sm text-slate-300 flex items-start gap-2.5">
                        <svg className="w-4 h-4 text-indigo-400 shrink-0 mt-0.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                        </svg>
                        <span>{imp}</span>
                      </li>
                    ))}
                  </ul>
                </div>

              </div>

            </div>
          ) : (
            <div className="h-full flex flex-col items-center justify-center p-12 border border-dashed border-slate-800 bg-slate-900/10 rounded-3xl min-h-[300px]">
              <svg className="w-16 h-16 text-slate-700 mb-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
              </svg>
              <h3 className="text-lg font-medium text-slate-400">Waiting for Upload</h3>
              <p className="text-sm text-slate-600 mt-1 max-w-xs text-center">Select a CV PDF and trigger the analysis to view recruitment score cards and improvements.</p>
            </div>
          )}
        </div>

      </div>
    </div>
  );
}
